### ISSUE TITLE
Fonts with different styles are registered with the same name.

### ISSUE THREAD

**Issue by ress997** [mshaugh/nerdfont-webfonts#1]
M+ fonts are all registered with the same name.
- https://github.com/mshaugh/nerdfont-webfonts/blob/master/build/mplus-nerd-font.css
- https://github.com/mshaugh/nerdfont-webfonts/blob/master/build/mplus-nerd-font-mono.css

If you look at the official website, you'll see that they are each slightly different fonts.
- https://mplus-fonts.osdn.jp/about-en.html

**Comment by mshaugh** [comment]
Hi, thanks for raising this. I was completely unaware of these variations in M+.

Closed by ea38404.
